diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
user.name=Valtrer lafuente
user.email=valterLafuente@yahoo.com.br
pack.buildbitmaps=false
core.symlinks=false
core.repositoryformatversion=0
core.filemode=false
core.logallrefupdates=true
core.bare=false
remote.origin.url=https://lafuente2019@github.com/lafuente2019/NuvemSO.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
